version: "3.4"

services:
    web:
        ports:
            - target: 80
              published: 7004
              protocol: tcp
              mode: host
        volumes: #多个配置文件的volumes配置会取并集
#            - ./deploy/stages/common/nginx:/etc/nginx/conf.d:ro
            - .:/app #dev环境才需要此配置
#        restart: always

